apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: voting-app
    name: result-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: voting-app
    name: result-app-pod




