apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    app: voting-app
    name: result-app-pod
spec:
  containers:
    - image: dockersamples/examplevotingapp_result
      name: result-app
      ports:
        - containerPort: 80


