apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    app: voting-app
    name: voting-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: voting-app
      name: voting-app-pod
  type: ClusterIP




